# Site settings
title: WNY Human Rights Clinic
email: wnyhrc@gmail.com
description: Home base for the efforts of the WNYHRC
baseurl: "wnyhrc"
url: "http://wnyhrc.org"
#twitter_username:
#github_username:

# Build settings
markdown: kramdown
